server:
  port: 80
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/resources?useSSL=false&useUnicode=true&characterEncoding=UTF-8\
      &serverTimezone=Hongkong"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-active: 15
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  thymeleaf:
    check-template: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true
    cache: false
mybatis:
  type-aliases-package: online.yangcloud.entity
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    online.yangcloud.mapper: debug
