server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: "jdbc:mysql://139.199.30.68:3306/resources?useSSL=false&useUnicode=true&characterEncoding=UTF-8\
        &serverTimezone=Hongkong"
      username: root
      password: Jhxz951129Jhxz
      initial-size: 5
      min-idle: 5
      max-active: 20
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  thymeleaf:
    check-template: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true
    cache: false
mybatis:
  type-aliases-package: online.yangcloud.entity
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    online.yangcloud.mapper: debug
