server:
  port: 8090
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    url: "jdbc:mysql://localhost:3306/resources?useSSL=false&useUnicode=true&characterEncoding=UTF-8\
               &serverTimezone=Hongkong"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长(毫秒),超过这个时长还没可用的连接则发生SQLException,默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  thymeleaf:
    check-template: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true
    cache: false
mybatis:
  type-aliases-package: online.yangcloud.entity
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    online.yangcloud.mapper: debug
