server:
  port: 80
spring:
  datasource:
    username: root
    password: root
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
backup: E:\\resources\\backup